Proyecto

```{r}
#1.1
library(tidyverse)
library(ggplot2)
library(lubridate)
library(dplyr)
```

```{r}
#1.2 y 1.3
deadhs_hand <- read_csv("deaths_handwashing.csv")

deadhs_hand

```

2 El alarmante número de muertes

2.1
```{r}
Prop <- deadhs_hand %>%
  mutate(deadhs_hand,proportion=deaths/births)
```

2.2
```{r}
print(Prop)
```
3. Muerte en las clínicas

```{r}
#3.1
ggplot(Prop,aes(x=year,y=proportion))+geom_line()
```

```{r}
#3.2
ggplot(Prop,aes(x=year,y=proportion,color=clinic))+geom_line()
```


4. Comienza el lavado de manos

```{r}
#4.1
clinic_1 <- read_csv("deaths_clinic_1.csv")
clinic_1
```


```{r}
#4.2
p_clinic_1 <- clinic_1 %>%
  mutate(clinic_1,proportion=deaths/births)
```


```{r}
#4.3
head(p_clinic_1)
```
5. El efecto del lavado de manos

```{r}
#5.1
ggplot(p_clinic_1,aes(x=date,y=proportion))+geom_line()
```

```{r}
#5.2
ggplot(p_clinic_1,aes(x=date,y=proportion))+geom_line()+labs(x="DATE",y="PROPORTION")
```


```{r}
#5.3
clinic_1
clinic_year <- clinic_1 %>%
  mutate(years=year(ymd(date)))%>%
  group_by(years)%>%
  summarize(mean_death = mean(deaths))
clinic_year
```


```{r}
ggplot(clinic_year,aes(x=years,y=mean_death))+geom_col()
```

6. Lavado de manos resultados

```{r}
#6.1
result_lavado <-clinic_1 %>%
  mutate(years=year(ymd(date)))%>%
  mutate(app_lavado=ifelse(years<1847,FALSE,TRUE))
result_lavado

```

```{r}
#6.2
fusion <- clinic_1 %>%
  inner_join(result_lavado, by = c("date"="date","births"="births","deaths"="deaths"),suffix = c("_clinic","_lavado"))%>%
  inner_join(p_clinic_1, by = c("date"="date","births"="births","deaths"="deaths"),suffix = c("_clinic","_p"))
  
ggplot(fusion,aes(x=date,y=proportion,color = app_lavado))+geom_line()

fusion
clinic_1
p_clinic_1
result_lavado
```
```{r}
#6.3

ggplot(fusion,aes(x=date,y=proportion,color = app_lavado))+geom_line()+labs(x="FECHA",y="PROPORCIÓN")

```



7. lavado de manos, menos muertes

```{r}
#7.1

result_lavado%>%
  group_by()%>%
  summarise(p_clinic_1,mean_muertes=mean(proportion))

result_lavado
p_clinic_1
```















